apiVersion: v1
kind: Service
metadata:
  name: oanda-trading-api-service
spec:
  type: NodePort
  selector:
    app: oanda-trading-api
  ports:
    - protocol: TCP
      port: 80  # Standard HTTP port for external access
      targetPort: 8080  # Port exposed by the container
      nodePort: 30000  # Custom NodePort for external access